# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI Workflow

on:
  pull_request:
    branches:
        - main
  push:
    branches:
        - main

defaults:
    run:
        shell: bash
        working-directory: ./

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm install
        - name: Run Tests
          run: npm run test